export type Route = {
  start: string;
  end: string;
  colors: [string] | [string, string];
  segments: number;
};

export const destinations = new Map<string, string>([
  ['lc', 'Lincoln Center'],
  ['cp', 'Central Park'],
  ['mw', 'Midtown West'],
  ['ts', 'Times Square'],
  ['un', 'United Nations'],
  ['ch', 'Chelsea'],
  ['so', 'Soho'],
  ['cht', 'Chinatown'],
  ['ws', 'Wallstreet'],
  ['br', 'Brooklyn'],
  ['le', 'Lower East Side'],
  ['gv', 'Greenwich Village'],
  ['ev', 'East Village'],
  ['gp', 'Gramercy Park'],
  ['est', 'Empire State Building'],
]);

export const routes: Route[] = [
  {start: 'lc', end: 'mw', colors: ['r'], segments: 2},
  {start: 'lc', end: 'ts', colors: ['g', 'b'], segments: 2},
  {start: 'lc', end: 'cp', colors: ['o'], segments: 2},
  {start: 'cp', end: 'lc', colors: ['o'], segments: 2},
  {start: 'cp', end: 'ts', colors: ['x', 'r'], segments: 2},
  {start: 'cp', end: 'un', colors: ['p'], segments: 3},
  {start: 'mw', end: 'lc', colors: ['r'], segments: 2},
  {start: 'mw', end: 'ts', colors: ['*'], segments: 1},
  {start: 'mw', end: 'est', colors: ['g'], segments: 2},
  {start: 'mw', end: 'ch', colors: ['b'], segments: 2},
  {start: 'ts', end: 'mw', colors: ['*'], segments: 1},
  {start: 'ts', end: 'lc', colors: ['r'], segments: 2},
  {start: 'ts', end: 'cp', colors: ['x', 'r'], segments: 2},
  {start: 'ts', end: 'un', colors: ['*'], segments: 2},
  {start: 'ts', end: 'est', colors: ['o', 'p'], segments: 1},
  {start: 'un', end: 'cp', colors: ['p'], segments: 3},
  {start: 'un', end: 'ts', colors: ['*'], segments: 2},
  {start: 'un', end: 'est', colors: ['x'], segments: 2},
  {start: 'un', end: 'gp', colors: ['g'], segments: 3},
  {start: 'ch', end: 'mw', colors: ['b'], segments: 2},
  {start: 'ch', end: 'est', colors: ['*', '*'], segments: 2},
  {start: 'ch', end: 'gp', colors: ['o'], segments: 2},
  {start: 'ch', end: 'gv', colors: ['r', 'g'], segments: 3},
  {start: 'ch', end: 'so', colors: ['p'], segments: 4},
  {start: 'so', end: 'ch', colors: ['p'], segments: 4},
  {start: 'so', end: 'gv', colors: ['o'], segments: 2},
  {start: 'so', end: 'ws', colors: ['*'], segments: 2},
  {start: 'cht', end: 'gv', colors: ['*', '*'], segments: 2},
  {start: 'cht', end: 'le', colors: ['b'], segments: 1},
  {start: 'cht', end: 'br', colors: ['r', 'o'], segments: 3},
  {start: 'cht', end: 'ws', colors: ['g', 'p'], segments: 1},
  {start: 'ws', end: 'so', colors: ['*'], segments: 2},
  {start: 'ws', end: 'cht', colors: ['g', 'p'], segments: 1},
  {start: 'ws', end: 'br', colors: ['x', 'b'], segments: 3},
  {start: 'br', end: 'ws', colors: ['x', 'b'], segments: 3},
  {start: 'br', end: 'cht', colors: ['o', 'r'], segments: 3},
  {start: 'br', end: 'le', colors: ['*'], segments: 3},
  {start: 'le', end: 'br', colors: ['*'], segments: 3},
  {start: 'le', end: 'cht', colors: ['b'], segments: 1},
  {start: 'le', end: 'gv', colors: ['*'], segments: 2},
  {start: 'le', end: 'ev', colors: ['x'], segments: 1},
  {start: 'gv', end: 'ch', colors: ['r', 'g'], segments: 3},
  {start: 'gv', end: 'gp', colors: ['x', 'p'], segments: 2},
  {start: 'gv', end: 'ev', colors: ['b'], segments: 2},
  {start: 'gv', end: 'le', colors: ['*'], segments: 2},
  {start: 'gv', end: 'cht', colors: ['*', '*'], segments: 2},
  {start: 'gv', end: 'so', colors: ['o'], segments: 2},
  {start: 'ev', end: 'le', colors: ['x'], segments: 1},
  {start: 'ev', end: 'gv', colors: ['b'], segments: 2},
  {start: 'ev', end: 'gp', colors: ['*'], segments: 2},
  {start: 'gp', end: 'gv', colors: ['p', 'x'], segments: 2},
  {start: 'gp', end: 'ch', colors: ['o'], segments: 2},
  {start: 'gp', end: 'est', colors: ['r', 'b'], segments: 1},
  {start: 'gp', end: 'un', colors: ['g'], segments: 3},
  {start: 'gp', end: 'ev', colors: ['g'], segments: 2},
  {start: 'est', end: 'ch', colors: ['*', '*'], segments: 2},
  {start: 'est', end: 'mw', colors: ['g'], segments: 2},
  {start: 'est', end: 'ts', colors: ['o', 'p'], segments: 1},
  {start: 'est', end: 'un', colors: ['x'], segments: 2},
  {start: 'est', end: 'gp', colors: ['r', 'b'], segments: 1},
];
